#!name=Locket Gold
#!desc=By: QuocChien 🙄

# Shadowrocket: 2024-11-11 09:00:00
# Lockket Gold
# Bản Quyền Thuộc Về Quốc Chiến ❤️‍🩹
# Thằng nào bán hoặc share mà không ghi nguồn là chó
# Tham Gia Nhóm Telegram Để Được Hỗ Trợ: https://t.me/shadowrocketunlockproapps
# Kênh Youtube: https://youtube.com/@quocchienn?si=2ygxKjhB_B1t6mRI

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/quocchienn/co_tien_khong/refs/heads/Quocchien_Module/locket_gold.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/quocchienn/co_tien_khong/refs/heads/Module/header.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
