#!name=Locket Gold
#!desc=By: Quốc Chiến

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/quocchienn/quocchien/refs/heads/Quocchien_Module/Locket.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/quocchienn/co_tien_khong/refs/heads/Quocchien_Module/delete_header.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
