#!name=Meitu Pro
#!desc=By: QuocChien 
# Module Meitu Pro Unlock - Quốc Chiến
# Hỗ trợ phiên bản 10.22.5
# Tham Gia Nhóm Telegram Để Được Hỗ Trợ: https://t.me/shadowrocketunlockproapps

[General]
skip-proxy = 127.0.0.1, ::1
bypass-system = true

[MITM]
hostname = *.meitu.com, *.meipai.com, *.meitudata.com

[Script]
# Sử dụng script từ GitHub để mở khóa Pro
http-response ^https://api\.meitu\.com/user/v\d+/subscription/status script-path=https://raw.githubusercontent.com/quocchienn/quocchien/refs/heads/Quocchien_Module/meitu_pro1.js, requires-body=true, max-size=0
http-response ^https://api\.meitu\.com/v\d+/pro/effects script-path=https://raw.githubusercontent.com/quocchienn/quocchien/refs/heads/Quocchien_Module/meitu_pro1.js, requires-body=true, max-size=0